### ISSUE TITLE
Smell suggestion: shorthand do syntax for multiline functions

### ISSUE THREAD

**Issue by pdgonzalez872** [lucasvegi/Elixir-Code-Smells#31]
Hi @lucasvegi ! ❤️ 

Here is something I can't put my finger on and kinda find it hard to comment on PRs and such (I kinda wish the formatter would handle this for us actually)

```elixir
def fun(args),
  do:
  args
  |> fun1()
  |> fun2()
  |> fun3()
  |> fun4()
```

If multiline, embrace the do/end syntax?
```elixir

def fun(args) do
  args
  |> fun1()
  |> fun2()
  |> fun3()
  |> fun4()
end
```

WDYT?

Thanks for all that you do! ❤️

**Comment by lucasvegi** [comment]
Hi @pdgonzalez872!

I agree with you that when we have multiple lines, the do/end notation makes the code more organized, clearly showing where the function ends. However, I'm not convinced that this is a code smell, since it is very low-level and more related to personal implementation preferences than a quality problem. It would be perfect to be included in a Linter, for example. I'll think about it more carefully. Thank you very much for the suggestion!

**Comment by pdgonzalez872** [comment]
> personal implementation preferences than a quality problem

Agree

> It would be perfect to be included in a Linter

Agree as well! Either the formatter or maybe a credo/recode check.

Thanks! ❤️
